# CI pipeline for azure builds
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  sdk: '3.0.100-preview-009812'
  buildConfiguration: 'Release'
  sln: './src/Lecs.sln'
  tests: './src/Lecs.Tests/Lecs.Tests.csproj'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: $(sdk)
- script: dotnet build --configuration $(buildConfiguration) /p:TreatWarningsAsErrors=true /warnaserror $(sln)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test $(tests) --logger "xunit;LogFileName=TestResults.xml"
  displayName: 'dotnet test'
- task: PublishTestResults@2
  displayName: 'publish test results to azure pipelines'
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TestResults.xml'
  condition: always()
