# CI pipeline for azure builds
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  sdk: '3.0.100-preview-009812'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: $(sdk)
- script: ./ci/build_release.sh
  displayName: 'Build'
- script: ./ci/test.sh
  displayName: 'Test'
- task: PublishTestResults@2
  displayName: 'Publish test results to azure pipelines'
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/artifacts/xunit.results.xml'
  condition: always()
- task: PublishCodeCoverageResults@1
  displayName: 'Publish test coverage results to azure pipelines'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/artifacts/coverage.cobertura.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/artifacts'
    failIfCoverageEmpty: true
  condition: always()
